FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY tests/e2e_tests.py .

ENV PYTHONPATH=/app

CMD ["pytest", "e2e_tests.py"]
