FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY tests/unit_tests.py .

ENV PYTHONPATH=/app

ENTRYPOINT ["pytest", "unit_tests.py"]
